baseURL = 'https://open-nexus.dev/'
languageCode = 'en-us'
title = 'Open Nexus'
theme = "hugo-brewm"

# Site parameters
[params]
  description = "Empowering LLMs with collaborative reasoning and advanced extraction capabilities"
  author = "Gavin Volpe"
  github = "https://github.com/gavinvolpe/nexus"
  twitter = "https://twitter.com/nexusframework"
  customCSS = ["css/custom.css"]
  
  # Theme specific parameters
  [params.site]
    name = "Open Nexus"
    description = "Empowering LLMs with collaborative reasoning"
    copyright = " 2025 Open Nexus"
  
  [params.author]
    name = "Gavin Volpe"
    email = "gavin@open-nexus.dev"
    github = "gavinvolpe"
    twitter = "nexusframework"

# Menu configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    url = "/docs/"
    weight = 2
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 3
  [[menu.main]]
    identifier = "community"
    name = "Community"
    url = "/community/"
    weight = 4

# Content configuration
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    unsafe = true

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

# Privacy
[privacy]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true